branches:
  only:
  - master
language: python
addons:
    apt:
        packages:
            - optipng
env:
  global:
  # wradlib.github.io
  - secure: "X4VWYvC8A0r4QVS8R/NKmIa2w4dlubW65n3BJeMdymiK8u9BX2rr1gmPhxam29NQYs6HRIXil2zzI/fHGvY6P/L4Ra2pyYmPjbG4G4j8mhUHkS8MxifO2V2RVVxgfSvvMG6XQigLz+wxGneAs4kGsmtN5RgK3HyUTCRLJWdK9m6WItBzcozP627w1QDCBOuuvV7x/sxhLjHgu2qKCXk6ZvHEULhwNd6EtnnNdvt6BgLWx91rlW7cLJqz1dGj1KjSXrxZvL8HhSBb/avr7dEWrybNBFUpRytk4tIcZrtJhumx7UmqhSNiFjkyHV9fOQjUyNbP/VHNQY6qlGxmz/re1VQmBNT9wrLDPzV2MpNCQLXTnvG+iSyl8CRc69s63RJogPA3rktHBvMJHL4/yWuv/q3ANYDTDR8mWMac+DLI0Q8kQZJ+ikSifuaVAwSxuxihLXyjt3fUQ3IcZi3N6lHzIGCNbhG33q3c3haRLELu4BNAHNpouhlR3H3Bek3ElvZCBt7tVma5X8WQxNQw2npjLg6TjfWuqL330x8MAGyK9xgJn26LKFAoI7DsAR6EaxjoClypJ9JuPAgZKsPe5mlpIV9NvVvGcWp/busXTk4/9ydj3dOnGGVybrgw5HC6rXF9H7tQBr2l6WXF33vYhw7wrgq+UBTyJCSV6jzFfir3hps="
python:
- 3.7
sudo: required
dist: xenial
install:
- pip install -r requirements.txt
script:
- make html
notifications:
  email:
    on_success: always
    on_failure: always

before_install:
  - git submodule update --init --recursive
  - mv content/templates/gallery.html plumage/templates/.
  - mv content/templates/base.html plumage/templates/.
after_success: make github 

